---
version: "3.8"

services:

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-bookstack}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=${DB_USER:-bookstack}
      - MYSQL_PASSWORD=${DB_PASSWORD:-bookstack}
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://wiki.joris.me
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=${DB_USER:-bookstack}
      - DB_PASS=${DB_PASSWORD:-bookstack}
      - DB_DATABASE=bookstack
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
