---
version: "3.8"

services:

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-bookstack}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=${DB_USER:-bookstack}
      - MYSQL_PASSWORD=${DB_PASSWORD:-bookstack}
    volumes:
      - bookstack_db:/config
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://wiki.joris.me
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=${DB_USER:-bookstack}
      - DB_PASS=${DB_PASSWORD:-bookstack}
      - DB_DATABASE=bookstack
      - AUTH_METHOD=oidc
      - AUTH_AUTO_INITIATE=false
      - OIDC_NAME=${OIDC_NAME:?error}
      - OIDC_DISPLAY_NAME_CLAIMS=preferred_username
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:?error}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET:?error}
      - OIDC_ISSUER=${OIDC_ISSUER:?error}
      - OIDC_ISSUER_DISCOVER=true
      - OIDC_DUMP_USER_DETAILS=true
    volumes:
      - bookstack_config:/config
    ports:
      - "127.0.0.1:6875:80"
    restart: unless-stopped
    depends_on:
      - bookstack_db

volumes:
  bookstack_db:
  bookstack_config:
